Language: python
python:
  - "3.7.8"
cache: pip

install:
  - pip install -r requirements.txt
script: pytest

sudo: required 
services: 
    - docker
before_install:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
       
    script:
        - sudo docker-compose build
        - sudo docker-compose up