version: "3"

services:
    mongosrv:
        image: "mongo"
        ports:
            - "5000:27017"
    servertokens:
        build: .
        depends_on:
            - mongosrv
        ports:
            - "5003:5003"
